### ISSUE TITLE
feat(appeal): check if appeal is allowed in submission page

### ISSUE THREAD

**Issue by AnsonH** [ZINC-FYP-2022-23/student-ui#9]
# Tasks

- [x] Collect data from the database to check the conditions
- [x] Disable grade appeal if the Auto Grader has not yet graded the submission and has not shown the score yet.
- [x] Show a warning sign near the appeal submission button when students get full marks
- [x] Fix: Enable the grade appeal button even when students get full marks
- [x] Disable the button in Content.tsx only if Appeal Attempt Left is zero

# Description

We should always check the user is allowed to make an appeal if he enters the `assignments/:id/appeal` page.

For example, suppose a user has no more appeal attempts left. The "Appeal your grade" button should be disabled and he cannot navigate to the appeal submission page (`assignments/:id/appeal`).

![image](https://user-images.githubusercontent.com/57580593/195984100-f966c01b-3da0-446d-8738-822eea4daa73.png)

However, he can still **manually type** the `assignments/:id/appeal` URL in the browser to navigate to the page! Therefore, the submission page should always check if he's allowed to make an appeal.

# Solution

Since both the assignment page (the screenshot shown above) and the appeal submission page contain logic on checking whether a user can make an appeal, I suggest refactoring the shared logic into a utility function (e.g. place inside the `utils/` folder).

### Logic
- Students cannot submit a grade appeal before the Auto Grader has graded the submission and shown the score.
- Students with zero appeal attempts left cannot submit a grade appeal.
- Students with full marks can still submit a grade appeal but a warning sign will be shown near the appeal submission button.
